// src/components/Building.tsx
import { useEffect, useState } from "react";
import { Card, CardContent, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import Bar from "@/components/ui/bar";

type BuildingPropsType = {
    name: string;
    quantity: number;
    cost: number;
    incScore: (amount: number) => void;
    buyBuilding: (name: string) => void;
    clickPower: number;
    speed: number;
    isManaged: boolean;
};

function Building({
    name,
    quantity,
    cost,
    buyBuilding,
    incScore,
    clickPower,
    speed,
    isManaged,
}: BuildingPropsType) {
    const [bar, setBar] = useState(0);
    const [isRunning, setIsRunning] = useState(false);
    const [internalDuration, setInternalDuration] = useState(speed);

    function clickMachine() {
        if (isRunning) {
            return;
        } else {
            setInternalDuration(speed);
            setIsRunning(true);
            setBar(100);
            setTimeout(function f() {
                incScore(clickPower * quantity);
                setIsRunning(false);
                setBar(0);
                setInternalDuration(0);
            }, speed);
        }
    }
    //useEffect(() => {
    //    if (isManaged) {
    //        clickMachine();
    //    }
    //}, [isManaged, clickMachine]);
    return (
        <>
            <Card className="w-full p-5">
                <CardContent>
                    <div className="pb-5 w-full flex items-center justify-between">
                        <CardTitle className="text-xl">{name}</CardTitle>
                        {/*<Progress className="px-5 rounded-md" value={bar} />*/}
                        <div className="gap-2 flex items-center">
                            <p>{quantity}</p>
                            <Button onClick={() => buyBuilding(name)}>{cost}🪙</Button>
                        </div>
                    </div>
                    <div className="flex items-center">
                        {quantity > 0 && (
                            <>
                                <Bar value={bar} duration={internalDuration} />
                                {clickPower * quantity}
                            </>
                        )}
                        {!isManaged && quantity > 0 && (
                            <Button onClick={() => clickMachine()}>▶️</Button>
                        )}
                    </div>
                </CardContent>
            </Card>
        </>
    );
}

export default Building;

// src/lib/Building.svelte
<script>
    import cx from "classnames";
    export let building;
    let {amount, cost, income, isRunning, isManaged} = building;
    if ($isManaged) {
        building.handleRun();
    }
</script>

<div class="bg-base-200 p-5">
    <div class="flex justify-between items-center">
        <div class="flex items-center">
            <button class={cx( "hover:bg-primary transition-all p-5 m-2 cursor-pointer rounded-xl" , $isManaged
                && "bg-primary" , )} on:click={building.handleRun}>
                <div class="w-16 rounded-xl">
                    <img src={building.image} alt={`Image of ${building.name}`} class="" />
                </div>
            </button>
            <p class="font-black text-2xl lg:text-sm">
                {building.name}
            </p>
        </div>
        <div class="flex items-center gap-3">
            <p class="font-black">{$amount}</p>
            <button class="btn btn-primary" on:click={building.handleBuy}>Buy: ${$cost}</button>
        </div>
    </div>
    <div class="relative">
        <div class="w-full bg-base-300 h-full min-h-8 flex">
            <div class={cx( `h-full min-h-8 transition-all `, $isRunning ? `w-full bg-primary
                duration-[${building.speed}ms]` : "duration-0 w-0 bg-secondary" , )}></div>
            <p class="absolute right-3 top-1">${$income * $amount}</p>
        </div>
    </div>
</div>
